<?php
/**
 * @file
 *  Extend search form with destination choose buttons.
 */

/**
 * Implements hook_form_alter().
 */
function easyddb_search_radios_form_alter(&$form, &$form_state, $form_id) {
  if ('search_block_form' !== $form_id) {
    return;
  }

  if ('search' !== arg(0)) {
    $options = array();

    $backends = search_get_info();
    $default = search_get_default_module_info();

    foreach ($backends as $backend_name => $backend_config) {
      $path = 'search/' . $backend_config['path'];
      $title = format_string('Search @backend', array('@backend' => $backend_config['title']));
      $title = l(t($title), $path);
      $options[$path] = $title;
    }

    $results_page = '';
    if ('search' === arg(0)) {
      $results_page = '-result';
    }

    $form['search_radios']['searches'] = array(
      '#type' => 'radios',
      '#required' => FALSE,
      '#options' => $options,
      '#default_value' => 'search/' . $default['path'],
      '#prefix' => '<div id="search-radios' . $results_page . '">',
      '#suffix' => '</div>',
    );

    $path = drupal_get_path('module', 'easyddb_search_radios');
    $form['#attached']['css'] = array(
      $path  . '/css/search_radios.css',
    );
    drupal_add_js($path . '/js/search_radios.js');
  }

}
